//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.12 at 09:22:02 PM IST 
//


package genrated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Flow }
     * 
     */
    public Flow createFlow() {
        return new Flow();
    }

    /**
     * Create an instance of {@link Flow.Command }
     * 
     */
    public Flow.Command createFlowCommand() {
        return new Flow.Command();
    }

    /**
     * Create an instance of {@link Flow.Command.Attributes }
     * 
     */
    public Flow.Command.Attributes createFlowCommandAttributes() {
        return new Flow.Command.Attributes();
    }

    /**
     * Create an instance of {@link Flow.Command.Next }
     * 
     */
    public Flow.Command.Next createFlowCommandNext() {
        return new Flow.Command.Next();
    }

    /**
     * Create an instance of {@link Flow.Command.From }
     * 
     */
    public Flow.Command.From createFlowCommandFrom() {
        return new Flow.Command.From();
    }

    /**
     * Create an instance of {@link Flow.Command.Attributes.Attr }
     * 
     */
    public Flow.Command.Attributes.Attr createFlowCommandAttributesAttr() {
        return new Flow.Command.Attributes.Attr();
    }

}
